### ISSUE TITLE
Conflict with Google Captcha plugin.

### ISSUE THREAD

**Issue by kprajapatii** [UsersWP/userswp#122]
There is conflict with the plugin  https://wordpress.org/plugins/google-captcha/.
Login, Registration & Reset Password via UWP pages not working if this plugin installed.

See https://userswp.io/support/topic/some-error-with-login-and-reset-password-with-members/

**Comment by wpdev10** [comment]
Need more details.

**Comment by kprajapatii** [comment]
Let me know, which more details you need?
