### ISSUE TITLE
myemail+substring@gmail.com gets error for username on registration

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#135]
Generally speaking WordPress and most other CMS allow myemail+substring@gmail.com during registration process.

However, it appears that when UsersWP is processing the email from the registration form this is resulting in an unacceptable username.

This doesn't happen with frontend post registration, when the same email is allowed to register, and the "+" is simply removed.

The registration page for UWP should allow registration and a username from a "myemail+substring" as "myemailsubstring" by simply removing the plus sign.

![screenshot 2018-01-17 at 4 48 03 am](https://user-images.githubusercontent.com/114659/35011711-0cdbd3ba-faff-11e7-912e-c2157c637947.png)

**Comment by wpdev10** [comment]
I think in this case, when a user enters a username like this and if we proceed with removing plus sign the user will not know that the correct username is without plus sign and he will not able to login to our site. So better we give error till we get the valid username from a user.

In the case of generating username from the email address, we can consider removing plus sign from the email address.

Let me know your thoughts!

**Comment by alexrollin** [comment]
WordPress allows emails with a plus sign.
This form has no username input.
The error is from the email resulting in Auto generated username.

**Comment by wpdev10** [comment]
Can you give me the link where you are testing the things?

In form builder, I can't remove the username field from registration form as it is the mandatory field. So how can I get the form with email and password but no username field?

**Comment by Stiofan** [comment]
The picture is a GD registration form not a UWP one...
