### ISSUE TITLE
Allow user to opt-out of user list

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#136]
Admin (or (maybe) other users)) should be able to set an option in the WP Edit Profile (not UsersWP profile) to opt-out of being included in the user list.

Related forum request:
https://wordpress.org/support/topic/admin-user-should-be-hidden-in-users-page/

**Comment by wpdev10** [comment]
We have added an option to privacy page for each user.

See https://github.com/UsersWP/userswp/pull/137

**Comment by Stiofan** [comment]
@wpdev10 this does not work with paging of users page, it still counts all users even excluded ones so there are extra blank pages
