### ISSUE TITLE
after login it should redirect to prev page

### ISSUE THREAD

**Issue by Stiofan** [UsersWP/userswp#141]
in login redirect, we should add top option, "Last User Page" and grab the referring page and redirect there if set.

**Comment by wpdev10** [comment]
https://github.com/UsersWP/userswp/pull/142

**Comment by Stiofan** [comment]
This does not seems to work in testing

**Comment by Stiofan** [comment]
go here https://ppldb.com/uwp-new/category/uncategorized/
login, you are redirected to account page not last user page
