### ISSUE TITLE
Delete user meta on removing from site of multisite network

### ISSUE THREAD

**Issue by wpdev10** [UsersWP/userswp#168]
Currently, we delete the user on the user_delete hook which will be not called if the plugin is not active for network-wide. So we have to use remove_user_from_blog hook to check if the user is having a single site or multiple sites. If the user is having a single site we can delete user meta else we can keep user meta as it is as the user is part of another site of the multisite network.

@Stiofan Need your inputs here.

**Comment by Stiofan** [comment]
Just grab the sites of user and loop through https://codex.wordpress.org/WPMU_Functions/get_blogs_of_user
If the user is being delete from the entire site and not just a multisite.
