### ISSUE TITLE
Filter to disable individual notifications.

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#176]
Please see: https://wordpress.org/support/topic/turn-off-your-notifications/#post-10024724

Thanks

**Comment by wpdev10** [comment]
Based on the support threads, They want to disable the notification to users on registration. The registration emails are sent to the users by WordPress by default and not by usersWP plugin. The function used to send email is a pluggable function so we can call it through a theme or a plugin and completely override it.

So, to disable those notifications, following code can be used:
`// Disable BOTH default WordPress new user notification emails
if ( ! function_exists( 'wp_new_user_notification' ) ) :
    function wp_new_user_notification( $user_id, $deprecated = null, $notify = '' ) {
        return;
    }
endif;`

You can copy the same function from WP core and put your custom condition at the starting of the plugin to check if you want to send it to user or admin using $notify variable.

This code can be put into the active theme's functions.php file. Let me know if more information required.
