### ISSUE TITLE
Settings text not responsive

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#185]
It can render OK on mobile, but doesn't adjust to change in display size once loaded.
From the users wp settings -> profile tab
![image](https://user-images.githubusercontent.com/114659/39096327-c4fc10be-464e-11e8-9036-933902490195.png)

From the Geodirectory integration page
![image](https://user-images.githubusercontent.com/114659/39097694-04eca998-4660-11e8-9f9a-bed35bfab598.png)

**Comment by wpdev10** [comment]
We should not consider this for now as we will use the default WP tabs in the settings.
