### ISSUE TITLE
Profile shortode

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#187]
Show a profile with a shortcode like [userswp_profile id=43423]

So an editor can show a user's profile in a post. Option to make specific tab active.

https://wordpress.org/support/topic/activity-short-code/

This issue is for activity only of a user: https://github.com/AyeCode/uwp-activity/issues/9

**Comment by wpdev10** [comment]
The issue is already created for activity addon at https://github.com/AyeCode/uwp-activity/issues/9 so closing from here.
