### ISSUE TITLE
Reviews tab using gravatar when comments are using UsersWP profile

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#188]
![uwp-profile-2-reviews](https://user-images.githubusercontent.com/114659/39099457-c8aec04e-467b-11e8-9259-17bc179e6ec5.jpg)

![uwp-profile-6-comments](https://user-images.githubusercontent.com/114659/39099458-c8cf7816-467b-11e8-858f-e0178ed6b22a.jpg)

**Comment by wpdev10** [comment]
Now we are showing post thumbnail for comments and listing thumbnail for reviews instead of user's avatar.

**Comment by alexrollin** [comment]
Good fix!

Orders entry shows 'nothumb' for order. Order has no image, order may have multiple products. User image doesn't seem right. but I couldn't think of an other alternative. Any ideas?
