### ISSUE TITLE
Comments 'not displayed' (because they are reviews) but ARE counted

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#201]
https://ppldb.com/uwptesting/profile/userswp/reviews/

users has 3 'comments' but it only displays 2, because one is a review and displayed on the reviews tab.

perhaps comments tab should show only count for comments, not reviews?

![image](https://user-images.githubusercontent.com/114659/39971441-2d8876c4-56fb-11e8-823a-cb6cbb703410.png)

![image](https://user-images.githubusercontent.com/114659/39971437-23e49184-56fb-11e8-945a-ef26f0f8ccae.png)

## Related topic
https://userswp.io/support/topic/only-seeing-2-of-3-comments/

**Comment by pol76** [comment]
yes we definitely need to separate review from comments...
