### ISSUE TITLE
ER: Redirect GD Add Listing URL

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#249]
ER: Redirect GD Add Listing URL

Add Listing could redirect to the UWP login form.
If the user needs to "Create account" then, if the user is automaticaly logged in, it would be great if they can be sent back to the page they were visiting.

mention: https://github.com/AyeCode/geodirectory/issues/563

**Comment by alexrollin** [comment]
Users who have requested this
https://wpgeodirectory.com/support/topic/registration-link-missing-from-add-listing/

**Comment by alexrollin** [comment]
I created a tracking issue in UWP for users waiting for UWP improvements
https://github.com/AyeCode/geodirectory/issues/563

**Comment by Stiofan** [comment]
Changes have been made in GD to just show a login and registration link (if reg enebled), these links are replaced by UWP so will change to those if UWP is active.
