### ISSUE TITLE
ER: UsersWP setting for redirect for GD Post Meta author link

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#253]
Add a setting in geodirectory integration to redirect GD Post Meta author links to the UWP profile URL

https://wpgeodirectory.com/support/topic/display-author-post-date-and-last-modification-date/#post-478868

https://wpgeodirectory.com/support/topic/how-to-add-listing-creator-avatar-verified-listing-on-details-page/

https://wpgeodirectory.com/support/topic/how-to-add-listing-creator-avatar-verified-listing-on-details-page/

**Comment by wpdev10** [comment]
Need inputs from @Stiofan
