### ISSUE TITLE
ER Control fields in users page (archive) - show all fields in list and grid

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#259]
Member requests showing all fields
https://userswp.io/support/topic/fields-not-displaying-in-users-page/#post-3836

**Comment by wpdev10** [comment]
Hi, It is possible to show the fields in grid view but it will break the layout if all members have not filled all fields. If users have filled a few fields then the grid will not display in proper rows and columns but it will display in proper columns only. That is the main reason we are not displaying all fields in grid view. Though one can display them easily if they want using a tweak in CSS.
