### ISSUE TITLE
Extensions page in UWP has a few bugs

### ISSUE THREAD

**Issue by Guust-Flater** [UsersWP/userswp#276]
.../wp-admin/admin.php?page=uwp-addons&tab=addons

* The "Install" buttons do not install the addons, but open a new tab going to the UWP page for the addon.
* The pricing seems to be wrong on some addons, eg Recaptcha and Social login.

Also, the plugins do not have an option to add the license in the plugins page.

Thanks

**Comment by wpdev10** [comment]
I have mostly used what is done in GD. But I will discuss with Stiofan if anything needs to be corrected.
