### ISSUE TITLE
113 user list page css

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#285]
![111](https://user-images.githubusercontent.com/114659/60390557-acd91780-9ad9-11e9-9d0f-194c418bb9c2.jpg)
![113](https://user-images.githubusercontent.com/114659/60390558-acd91780-9ad9-11e9-83ff-dbbf246ebc76.jpg)

**Comment by wpdev10** [comment]
We are keeping CSS based on the theme but I will make sure the basic layout displays properly for all the forms and pages.
