### ISSUE TITLE
ER UX on login/reg forms

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#297]
Request from members
https://userswp.io/support/topic/after-registration-doesnt-send-activation-email/#post-4934

 - Add a loading icon/image to show that the submit button is doing something
 - Optional warning/validation messages - specifically, password must be 7 char or more
 - 
![image](https://user-images.githubusercontent.com/114659/62642412-f40ebf80-b945-11e9-84dd-4e5f6c29e402.png)

**Comment by wpdev10** [comment]
This is done with bootstrap design release.
