### ISSUE TITLE
ER Redirect param for register and login shortcodes

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#302]
https://userswp.io/support/topic/different-redirects-set-in-shortcode/

**Comment by wpdev10** [comment]
I think providing param in the shortcode is not good option for security concerns. Instead, we have provided filter "uwp_redirect_url" which can be used to change the redirect URL with minor customization.

**Comment by alexrollin** [comment]
can you provide an example of this for

1 - all login forms
2 - login form on a particular page with slug /add-listing/

**Comment by wpdev10** [comment]
Here is the example of using that filter:

`add_filter('uwp_redirect_url', 'uwp_redirect_url_cb', 10, 1);
function uwp_redirect_url_cb($redirect_to){

    if(is_page('test-login')){ // Condition to check for particular page with slug
	    return home_url(); // Change to whatever URL you want to redirect to
    }

    return $redirect_to;
}`

On add listing page, the login form is used from the WP default login form and not the UWP login form. So that is not handled by UWP.
