### ISSUE TITLE
ER Export activation link

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#304]
If a member is migrating to GeoDirectory they will probably need to do some sort of email merge type mailing that will include the username, activation link, and perhaps a link to the listing.

To allow members more flexibility, would it be possible to include the user activation link in the export? Perhaps as an option? This way the member can send a custom email on their own with needing the system email. 

https://wpgeodirectory.com/support/topic/importing-users-and-or-then-listings/#post-510127

**Comment by wpdev10** [comment]
It is like a specific case of that site and generally exporting the activation link is not a good option as it expires in 24 hours. If they want to stop notifying while import, we have added a filter for that which they can modify to stop sending emails. We shouldn't export passwords as well. The one option is to send an email with usernames and forgot the password link to recover/create the password for the imported users.
