### ISSUE TITLE
Profile Listings Tab Feedback

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#308]
Add a title filter to the listing display
![image](https://user-images.githubusercontent.com/114659/66515536-92063e00-eadf-11e9-8fe1-2f95a61b6f75.png)

Respect ordering in settings for CPT type subtabs.

![image](https://user-images.githubusercontent.com/114659/66516460-59676400-eae1-11e9-8012-c75893f953cd.png)

Remove old tabs setting
![image](https://user-images.githubusercontent.com/114659/66516754-178aed80-eae2-11e9-869c-83ec5fdd9bd7.png)

Link to tabs settings
![image](https://user-images.githubusercontent.com/114659/66516804-2f627180-eae2-11e9-83fa-def3fce65841.png)

Make sure invoice and subscription information is not visible to anyone but the profile owner

![image](https://user-images.githubusercontent.com/114659/66516469-5ec4ae80-eae1-11e9-9296-dbae4ec26b02.png)

![image](https://user-images.githubusercontent.com/114659/66516513-756b0580-eae1-11e9-8668-b132827022ba.png)

**Comment by Stiofan** [comment]
1. I'm not sure we will need a filter for a users posts?  Usually a user will have very few but if its requested then we will add it.

2. Those inputs are always in alphabetical order, the actual order comes from the CPT order input.

3. Old tabs settings, yup i will remove them after i have created the conversion script but we need all addons that use it to be converted first. 

4. Visibility, this should not fall on UWP but WPI, i think Patrick already added changes for this.
