### ISSUE TITLE
Cropping tool of cover photo not working 

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#33]
The Cropping tool of cover photo does work correctly.

1) The modal that opens for the cropping tool is open at the bottom of the screen 
![capture](https://cloud.githubusercontent.com/assets/25163253/22572174/7bcaf07a-e968-11e6-8358-a3df0c8043e9.JPG)

2) When I select an image for Cropping, I cannot close the window to start over (the X in the top right corner does nothing). I have to complete cropping the image to get out of there.

3) The image always get cropped differently from what I selected and overall the quality of the picture is lowered.

Thanks

**Comment by Stiofan** [comment]
![derp](https://cloud.githubusercontent.com/assets/10433311/22705240/acbca7a2-ed62-11e6-9ecc-76e1297a60f7.png)

File size prob, this is on multisite: https://ppldb.com/userswp/

**Comment by mistergiri** [comment]
https://github.com/mistergiri/userswp/commit/c825d5904e814f5d9f4c6bb36682bcfd725a1398
