### ISSUE TITLE
BUG UX - some fields cannot have visibility conditions so vis condition filter should be removed

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#335]
First name, Last name, Display name, username, email and bio are the default fields. The "Is public" is used to target the custom fields created other than this. There are multiple places where we need to display the above fields and that's why we could not make it private. We may hide the option for the above fields.

https://userswp.io/support/topic/potential-privacy-fail/#post-6747

**Comment by wpdev10** [comment]
This will be removed in the next version. I am going to push the code for this today.
