### ISSUE TITLE
Bug - GD DAshboard broken with UWP installed - please add uwp_dashboard

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#337]
GD Dashboard is currently broken if UWP is installed (my listings going to blank page)

uwp_dashboard should be added.
currently uwp dashboard can only be shown with login widget, and there is no control in UWP to hide the login widget for logged out users (to only show the dashboard for logged in users)

uwp_dashboard

https://wpgeodirectory.com/support/topic/gd-dashboard-stopped-working/

**Comment by wpdev10** [comment]
If we get more requests from customers for adding UWP Dashboard then we will add it. For now closing this issue.
