### ISSUE TITLE
New Addon - Restrict Access - Memberships, Roles

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#344]
Restrict access, memberships, roles
https://userswp.io/support/topic/restrict-access-to-visitors/#post-7236

**Comment by pol76** [comment]
This should be easy to do, just add a field in the registration form builder named  "Role" and in the options add the list of available roles.

Content control can be later used to restrict access to certain content by role.
Role Editor can be used to play around with existing roles and add new roles.

Thanks

**Comment by pol76** [comment]
This should be added to core.
