### ISSUE TITLE
Bug update strings for grammer

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#346]
https://userswp.io/support/topic/change-wording-within-login_details/#post-7364

 [#login_details#]

It currently says: Password you have entered while registration.

Can it be changed to:
Password you entered during registration.

Thanks.

Thank you for signing up for xxxxxxxxxx!

We are looking forward to welcoming you to our next event.

Your login Information :

Username: email@email.com

Password: Password you have entered while registration.

You can login here: https://xxxxx.com

**Comment by wpdev10** [comment]
It can be changed using a filter "uwp_register_mail_message". I am changing the text for password message. Rest of the text can be added or modified via filter as per requirements.
