### ISSUE TITLE
ER Support for UWP fields as native author and user meta for builders

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#354]
it is possible to show a custom field value with a builder by using "geodir_mycustomfieldkey"

so uwp_mycustomkey would be excellent.

Further, to support field queries as-native would be great too, like these from BB

https://kb.wpbeaverbuilder.com/article/572-field-connection-shortcode-index-themer

![image](https://user-images.githubusercontent.com/114659/76341075-d00cc580-62fc-11ea-844a-109085e016cf.png)

![image](https://user-images.githubusercontent.com/114659/76341085-d4d17980-62fc-11ea-912f-205662d31007.png)

**Comment by wpdev10** [comment]
This can be done in the role/membership manager add on but if needed in the core then also fine. Will need inputs from @Stiofan

**Comment by wpdev10** [comment]
We have added this feature in recent version 1.2.2.4 which will work with 'uwp_mycustomkey'
