### ISSUE TITLE
Break down profile header into 4 shortcodes / blocks/ widgets

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#364]
Please breakdown the profile header shortcode into 4 elements:

UWP > Profile Header (output the big banner)
UWP > Profile Avatar (output the avatar)
UWP > Profile Name (output the profile name)
UWP > Profile Activity Summary (output the number of posts, comments and other activites)

This way we can customize the header via page builders.

Thanks

**Comment by pol76** [comment]
Settings for Avatar -> Avatar Size not working. When used individually the avatar is set at full width.

**Comment by wpdev10** [comment]
@pol76 Are you testing in local or any staging site? If you are in the localhost then we use the default avatar image to display in local as the gravatar URL will not work with the localhost and images will display broken with an alt tag. We pass the size to gravatar which will return the image URL with proper image size. We may limit the image height and width by size parameter if we have to but the URL returned by gravatar will have height and width from our size parameter. 

For points #2 and #3 I will check and implement some solution soon.

**Comment by pol76** [comment]
@wpdev10 Hi Rahul, yes I'm testing in local. Many ppl do develop on local and we should have the default image simply behave like the gravatar or uploaded avatar. 150px X 150px, that will solve it all.

Thx

**Comment by pol76** [comment]
@wpdev10 @Stiofan 

I just tested the latest and none of this is done?

1) This is not only a localhost problem http://ppldb.com/uwp/profile/paolo/
This is a problem for anyone not using a gravatar.
Default avatar or user uploaded pictures should behave **exactly** like gravatar.

2) Please see http://ppldb.com/uwp/profile/paolo/ 
this should look exactly like this: http://ppldb.com/uwp/profile/admin/

3) I still can't determine the height of the banner unless I'm missing something.  

Thanks

**Comment by wpdev10** [comment]
Hi,

I have applied the fix for the avatar size but I need some more information or screenshot about the other 2 points.

**Comment by Stiofan** [comment]
@wpdev10 please add a setting for banner height

**Comment by wpdev10** [comment]
This is done. I have added settings for both avatar and banner height and width.
