### ISSUE TITLE
ER Password Strength settings

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#370]
Allow the user to adjust password strength requirements in the password field

Help text (with instructions about how to make a password that apsses the test)
Min length
Max length
Force strong password

![image](https://user-images.githubusercontent.com/114659/81753842-fa256400-94b4-11ea-94b7-338377ce9cea.png)

Ultimate member settings
![image](https://user-images.githubusercontent.com/114659/81753863-07425300-94b5-11ea-83ac-f6b59e66b7b9.png)

**Comment by wpdev10** [comment]
We have added settings for min and max limit for password and min limit for the username as a setting in registration settings tab.
