### ISSUE TITLE
Buggish - Make select field placeholder option to match GD select field placeholder

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#373]
Currently there isn't a way to set a placeholder (it would seem)

**Comment by alexrollin** [comment]
from kiran - 
in v2.0.0.82 we fixed for GD https://github.com/AyeCode/geodirectory/commit/683aca8aec6844696316e12abbfb187f52d41fc5#diff-4e56e6988d0d758df3fa870d2ddff08aR685

**Comment by wpdev10** [comment]
Fixed.
