### ISSUE TITLE
UX  - Hide "Create account" automatically if registration is disabled

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#375]
right now it requires a template override. Please help the users.

**Comment by alexrollin** [comment]
This should be automagical

**Comment by Stiofan** [comment]
Unfortunately lots of admins don't realises this is a WP setting, and if the links shows then we can at least show them a message that it is disabled, if we hide it then they will just think UWP is broken IMO.

**Comment by wpdev10** [comment]
Solution-1: We should create a doc for this instead of adding it to the core. 
Solution-2: We can do it in core and just display a notice on the admin side and on the registration form on the frontend side. Need inputs @Stiofan @alexrollin

**Comment by Stiofan** [comment]
Maybe we need a setting in setup wizard to set registration active?

**Comment by wpdev10** [comment]
We have implemented this feature in setup wizard.
