### ISSUE TITLE
User meta data for SEO if possible

### ISSUE THREAD

**Issue by wpdev10** [UsersWP/userswp#378]
Customer request:

Is there any way that every user’s profile page has a unique meta title (their name) and meta description (their bio)? This is important for SEO, so the search engines will not see the pages as duplicates. It will be better if it can also generate a “Person” json ld structured data.

**Comment by Stiofan** [comment]
@pol76 ur advice is needed here.

**Comment by pol76** [comment]
Yup, sounds like a logical thing to do...
