### ISSUE TITLE
Show in what locations? MultiSelect buggy

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#38]
Hi Giri,

why doesn't the multiselect field Show in what locations? of the custom fields work like GD?

![capture](https://cloud.githubusercontent.com/assets/25163253/23047368/02341922-f475-11e6-8624-df60cdf9653a.JPG)

I find it hard to scroll and select like that.

Please fix it.

Thanks,

**Comment by mistergiri** [comment]
https://github.com/mistergiri/userswp/commit/023144322b405a2b6031e1b8fd6b1d38ae147c43
