### ISSUE TITLE
Action Hooks

### ISSUE THREAD

**Issue by stigzler** [UsersWP/userswp#385]
Hi - sorry, but I wonder if you'd be prepared to help a newb to php + wordpress plugin management?

I like your plugin - super slim. However, looking to develop a plugin to catch user registrations/password resets and then populate other web apps (MantisBT and PhpBB) with the user details, to allow one registration to serve all apps. 

Sadly, I'm falling at the first hurdle. I can't figure out how to tap into the action hooks in userswp. I've pulled out all the "do_action" from your source, but they just don't trigger my add_actions in my plugin code. 

Forgive me - very new to this - so probably a silly oversight.

**Comment by wpdev10** [comment]
We may need to check your code as it should work fine because we are using the default WordPress do_action and do_filter in our core plugin. You may take help from an expert WordPress developer for this if you are new at this. We don't provide support for the custom development here so you can get help from the WordPress developer for this and if any issues related to our plugin code then you can raise a ticket and we will fix asap.

**Comment by wpdev10** [comment]
You can find 'do_action' in the whole userswp folder to get the list of hooks using some tool like sublime or PHPStorm. These tools are generally used by developers.

**Comment by stigzler** [comment]
Ah thanks. Yeah, Patrik, I'd done this in Visual Studio. Problem being none of the do_actions are being detected by my plugin. For exaple:

wp_login
uwp_after_process_login

are not detected by my plugin. However:

uwp_loaded

is. Just can't seem to hook into any of the main do_actions in userswp. I've made a post on stackexchange - let's see if they can help.

Steve

------ Original Message ------

**Comment by wpdev10** [comment]
You will need to add all the actions after 'uwp_loaded'. You can check our addon's code which are also a plugin but running all actions and filters from the core UsersWP plugin. I am sure you might be missing something. If a developer works on this then there should be no such issues. Are you using add_action() to hook into the hook in our core plugin?

**Comment by stigzler** [comment]
Hey Patrik. Thanks for the response. I know it's out of the policy, so really appreciate it. I believe I am. Here's my code:

<?php
/**
 * Plugin Name: Signup Sync (OGZ)
 * Plugin URI: http://www.mywebsite.com/my-first-plugin
 * Description: Syncs other databases on signup
 * Version: 1.0
 * Author: stigzler
 * Author URI: http://www.magoarcade.org
 */

defined( 'ABSPATH' ) or die( 'No script kiddies please!' );

// Log File ==========================================================
function write_log ($txt) {
    $myfile = fopen("stigzler-log.txt", "a") or die("Unable to open file!");
    fwrite($myfile,  "\n". date('h:i:s ', time()) . $txt);
    fclose($myfile);
}

function ogz_uwp_loaded() {
    write_log('uwp_loaded triggered');
    }
add_action('uwp_loaded', 'ogz_uwp_loaded');

function ogz_uwp_after_process_register( $data, $user_id ) {
    $user_info = get_userdata($user->ID);
    write_log('uwp_after_process_register: ' . "\r" . $user_info->user_login . "/r" . $user_info->ID);
}
add_action('uwp_after_process_register', 'ogz_uwp_after_process_register', 10, 2);

function ogz_uwp_after_process_login() {
    write_log('uwp_after_process_login triggered');
}
add_action('uwp_after_process_login', 'ogz_uwp_after_process_login');

?>

uwp_loaded does fire. However, neither uwp_after_process_login nor uwp_after_process_register do. I'm not sure what I'm doing wrong! :(

------ Original Message ------

**Comment by wpdev10** [comment]
You should try loading all the things on 'plugins_loaded' hook. Check out our add on's code and you will get an idea. I can't help more with customization.
