### ISSUE TITLE
Shortcode for recent reviews by author

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#391]
Currently gd shortcode doesn't take author arguement and userswp tab is not available as a shortcode.

Please add a shortcode for reviews reviews that takes the current_user or current_author or author id argument for use in custom tabs and on other pages and posts.

**Comment by wpdev10** [comment]
For reviews, it would be good to add this feature to GD addon instead of UWP as this is a specific feature to GD reviews. If you talking about the comments then we may add a shortcode for that in UWP core. Need thoughts from @Stiofan for this.
