### ISSUE TITLE
ERROR: in registration form clear all fields

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#40]
I just did a test and enter non matching password while registering.

I got this error : ERROR: Passwords do not match.

and all fields where lost, so I have to enter them again.

I'd prefer if only the password fields would be deleted in case of an error. Having to re-enter the entire form is not good UX.

Thanks.

**Comment by mistergiri** [comment]
https://github.com/mistergiri/userswp/commit/023144322b405a2b6031e1b8fd6b1d38ae147c43
