### ISSUE TITLE
Gender field - default option values bug

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#402]
Default Options values of the Gender field are:

Select Gender/,Male,Female,Other

It is my understanding that "Select Gender" should be the placeholder and not a selectable option. 

On the register page, it adds the placeholder "Choose Gender", instead of "Select Gender" and I'm not sure where it is taking that from.: https://wpgeo.directory/userswp/register/

While in the lightbox form "Select Gender" is an option that can be selected:

Please see https://paste.pics/A27TR

Thanks for fixing it.

**Comment by wpdev10** [comment]
We have added a new option 'Placeholder:' in the custom field in the form builder in the last version and if this option is not set then by default it will display "Choose xxx" for all dropdowns. So the first blank input is not needed in the custom field "Option Values".

**Comment by wpdev10** [comment]
I have just fixed the issue regarding placeholder not loaded in the dropdown in popup by reinitializing the select2 in the lightbox.
