### ISSUE TITLE
Templates shouldn't be counted in profile

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#407]
Templates are part of Elementor and shouldn't be counted in profiles.

Only the CPTs that have an integration should appear there:

Products, Jobs, Downloads, Places, and all GD stuff...

https://ppldb.com/uwp/profile/admin/

Thanks

**Comment by wpdev10** [comment]
Our logic is we display all public post types and templates is a CPT of elementor and that's why it's displaying. We have to find out such things and put them in the ignore list one by one then. @pol76 @Stiofan

**Comment by Stiofan** [comment]
What about a setting that lists all public CPTs, and it has a select option
* Show All (we set this as default for any GD or plugin we integrate with like Woo or EDD)
* Show Author
* Hide

Thoughts?

**Comment by wpdev10** [comment]
How about giving multiselect box with all the public CPTs and allow admin to choose which to display and we can give two settings for displaying CPTs for loggedin and non logged in users profiles.

**Comment by pol76** [comment]
_How about giving multiselect box with all the public CPTs and allow admin to choose which to display and we can give two settings for displaying CPTs for loggedin and non logged in users profiles._

Sounds good to me.

**Comment by wpdev10** [comment]
We have added an option in the backend for this.
