### ISSUE TITLE
We need to fix the badges on user's profile

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#409]
![image](https://user-images.githubusercontent.com/25163253/93649817-76cfce00-f9d2-11ea-8109-67d681f9cd9c.png)

@basanta can we fix the design of this page?

@Stiofan can we add basanta to all repos? 

Thanks

**Comment by basantaux** [comment]
@pol76 please check and let me know if that works?

![User-post-list-header-2 Copy 5](https://user-images.githubusercontent.com/52257358/93790533-c8858c00-fc50-11ea-8f4d-082e1e05b58b.png) 
![User-post-list-header-2 Copy 6](https://user-images.githubusercontent.com/52257358/93790511-c0c5e780-fc50-11ea-802e-ff8fa2620dc9.png)

**Comment by wpdev10** [comment]
Duplicate issue of https://github.com/UsersWP/userswp/issues/411
