### ISSUE TITLE
Better UI for badges on profile

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#411]
hi Rahul,

when there are a lot of badges the design of the profile suffers a lot. See:

![uwp_profile_mess](https://user-images.githubusercontent.com/25163253/93791100-6a798a00-fbf9-11ea-95e4-9ce9426cbe40.JPG)

I asked Basanta to design something better. Can we implement his design quickly?

![User-post-list-header-2 Copy 5](https://user-images.githubusercontent.com/25163253/93791156-7f561d80-fbf9-11ea-8bd7-af715676be22.png)
![User-post-list-header-2 Copy 6](https://user-images.githubusercontent.com/25163253/93791158-7feeb400-fbf9-11ea-851e-57fd11466979.png)

Thanks!

**Comment by Stiofan** [comment]
@wpdev10 this can use the AUI greedy menu just like the GD tabs, if u have any questions just ask me.

**Comment by wpdev10** [comment]
We have added the greedy menu.
