### ISSUE TITLE
Time field looks like this on the backend user's profile page.

### ISSUE THREAD

**Issue by laranz** [UsersWP/userswp#428]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/208945/98912321-edc5a680-24eb-11eb-9a4e-dd36b6abf1d9.png">

**Comment by wpdev10** [comment]
This is because we are not loading only compatibility related CSS on this page from AUI. If you change the setting from the Settings->AyeCode UI->Backend->Load CSS to Full Mode then you will see it looks proper.
