### ISSUE TITLE
Privacy setting, let user decide doesn't work

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#47]
Hi Giri,

I can't save any of the custom field to use the "Let user decide" option, I can only save Yes or No. 

The privacy page is blank.

You can test it in my dropct demo.

Thanks

**Comment by mistergiri** [comment]
Paolo,

I have added an extra value in enum. So if you have not deleted and recreated uwp tables, then that would be the problem.

https://github.com/mistergiri/userswp/blob/master/includes/class-users-wp-activator.php#L205

Privacy page should not be displayed if there in no Let me choose items. So let me fix that part.

Thanks
