### ISSUE TITLE
WPMU

### ISSUE THREAD

**Issue by Stiofan** [UsersWP/userswp#68]
discuss WPMU issues here

**Comment by mistergiri** [comment]
https://codex.buddypress.org/getting-started/installation-in-wordpress-multisite/#b-network-wide-activation-buddypress-root-blog-in-secondary-site

**Comment by Stiofan** [comment]
** WPMU Activation defaults:**
_WPMU:_
DB: one on main site
Pages: Create for main site only and redirect all there,

_Single site:_
DB: one
Pages: Create for that site only


**Constants** (if network activated)
`define( 'UWP_ROOT_PAGES', $blog_id );` 
Create pages on this site and redirect all to there.

`define( 'UWP_ROOT_PAGES', 'all' );`
Create pages on all sites and use them for each site
