### ISSUE TITLE
File Upload not working 

### ISSUE THREAD

**Issue by korchung** [UsersWP/userswp#71]
To replicate:

#1 Upload a file on the "File Upload" field. 

#2 Click on "Update Account"'

#3 Go to a "Multiselect" field and add a new object. 

#4 Clicking on "Update Account" will remove the file from "File Upload" field.

**Comment by mistergiri** [comment]
@Stiofan Kc reported this bug 2 days back. This bug is already fixed and the fixed version already uploaded to the test site.
