### ISSUE TITLE
please improve info in help tooltip for multiselect field

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#94]
We have the same info for both radio, select and multiselect.
Please provide 3 different examples for each type.
Thanks

**Comment by Stiofan** [comment]
i removed the part about multiselect only, is this enough?

**Comment by pol76** [comment]
can we add proper instructions for multiselect? Right now ppl have to guess what to enter as options...

**Comment by Stiofan** [comment]
Please check now?
