### ISSUE TITLE
Manage Register Form Fields issue

### ISSUE THREAD

**Issue by pol76** [UsersWP/userswp#97]
Please make sure that fields added are auto saved and i don't have to save them to make them appear.

Thanks

**Comment by pol76** [comment]
Also please remove the grey X from the default fields. If they can't be deleted that is confusing.

Thx

**Comment by Stiofan** [comment]
I had left it greyed out so when u hover over it it tells u its a default field and can't be removed, but if u think we should just remove it i'll do that, let me know.

**Comment by Stiofan** [comment]
register fields will auto save on add now

**Comment by pol76** [comment]
I would remove the grey X. If they are not there, ppl will stop thinking they can delete them...
